openapi: 3.0.0
info:
  title: Twitter Recent Search API - Grupo 4
  description: |
    Documentación del endpoint `/2/tweets/search/recent` de la API de Twitter.
    Este endpoint permite buscar tweets recientes basados en una consulta específica.
    
    Proyecto realizado como parte del deber del **Grupo 4**:
    - **Sebastian Aisalla**
    - **Tatiana Gualpa**
    - **Marcelo Maisincho**
    - **Stalin Yungan**
  version: 1.0.0

servers:
  - url: https://api.twitter.com/2
    description: Servidor base de la API de Twitter.

paths:
  /tweets/search/recent:
    get:
      summary: Buscar tweets recientes
      description: |
        Este endpoint devuelve los tweets más recientes que coinciden con una consulta específica.
        Los resultados incluyen información como el texto del tweet, el autor, la fecha de creación y métricas como likes y retweets.
      parameters:
        - name: query
          in: query
          required: true
          description: |
            Consulta de búsqueda para obtener tweets. Puede ser un hashtag, palabra clave o frase.
          schema:
            type: string
            example: "#tecnologia"
        - name: max_results
          in: query
          required: false
          description: |
            Número máximo de tweets a devolver. El valor debe ser **100**.
          schema:
            type: integer
            default: 0
            example: 100
        - name: tweet.fields
          in: query
          required: false
          description: |
            Campos adicionales que se pueden incluir en la respuesta, como métricas y autor.
            Ejemplos: `text`, `created_at`, `author_id`, `public_metrics`.
          schema:
            type: string
            example: "text, created_at,author_id,public_metrics"
      responses:
        '200':
          description: Respuesta exitosa con los tweets encontrados.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "1234567890123456789"
                        text:
                          type: string
                          example: "El futuro de la tecnología se encuentra en #IA y #BigData. #innovacion"
                        created_at:
                          type: string
                          format: date-time
                          example: "2024-12-11T03:09:58.000Z"
                        author_id:
                          type: string
                          example: "1846404697231347712"
                        public_metrics:
                          type: object
                          properties:
                            retweet_count:
                              type: integer
                              example: 25
                            like_count:
                              type: integer
                              example: 50
        '400':
          description: Error de solicitud debido a parámetros incorrectos.
          content:
            application/json:
              example:
                error: "Parámetro 'query' es obligatorio."
        '401':
          description: No autorizado. Token Bearer faltante o inválido.
          content:
            application/json:
              example:
                error: "No autorizado. Proporcione un token Bearer válido."
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              example:
                error: "Error interno. Intente nuevamente más tarde."
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []

tags:
  - name: Tweets
    description: Operaciones relacionadas con la búsqueda de tweets recientes.

examples:
  - name: Ejemplo de solicitud
    description: Ejemplo de solicitud al endpoint `/2/tweets/search/recent`.
    value:
      method: GET
      url: "https://api.twitter.com/2/tweets/search/recent?query=%23tecnologia&max_results=10&tweet.fields=created_at,author_id,public_metrics"
      headers:
        Authorization: "Bearer AQUI_SU_TOKEN"
